/**
 * Centralized theme and color palette definitions for Flux Flow CLI.
 */

export const CHAOS_PRESETS = [
    {
        name: 'Cyan Cyberpunk',
        text: 'cyan',
        textMuted: '#4da6b8',
        textDim: '#2d6d7a',
        textInverted: 'black',
        border: 'cyan',
        borderMuted: '#1a5966',
        borderDim: '#0f3840',
        bg: undefined,
        cardBg: '#061e24',
        highlightBg: '#092b33',
        activeBg: '#0e3e4a',
        inputBg: '#092b33',
        inputBorder: '#092b33',
        inputText: 'cyan',
        inputPlaceholder: '#2d6d7a',
        inputPrompt: 'cyan',
        codeBg: '#020d10',
        codeBorder: '#1a5966',
        userMsgBg: '#092b33',
        userMsgBorder: '#092b33',
        userMsgText: 'cyan',
        diffRemovalBg: '#3a0c1a',
        diffAdditionBg: '#0c3a32',
        diffRemovalText: '#ff4d88',
        diffAdditionText: '#00ffaa',
        diffRemovalHighlightColor: '#ff1a66',
        diffRemovalHighlightBg: '#590022',
        diffAdditionHighlightColor: '#00ffcc',
        diffAdditionHighlightBg: '#00593b',
        diffRemovalNum: '#ff4d88',
        diffAdditionNum: '#00ffaa',
        diffRemovalPrefix: '#ff1a66',
        diffAdditionPrefix: '#00ffcc',
        primary: 'cyan',
        secondary: 'blue',
        accent: 'magenta',
        success: 'green',
        warning: 'yellow',
        danger: 'red',
        info: 'blue',
        statusOn: 'cyan',
        statusOff: '#2d6d7a',
        logoTextAnsi: '\x1b[1;36m',
        logoBodyAnsi: '\x1b[36m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#00ffff', '#0088ff'],
    },
    {
        name: 'Magenta Vaporwave',
        text: 'magenta',
        textMuted: '#c451d6',
        textDim: '#7d2b8a',
        textInverted: 'black',
        border: 'magenta',
        borderMuted: '#5e1b69',
        borderDim: '#3b0f42',
        bg: undefined,
        cardBg: '#240729',
        highlightBg: '#310938',
        activeBg: '#470e52',
        inputBg: '#310938',
        inputBorder: '#310938',
        inputText: 'magenta',
        inputPlaceholder: '#7d2b8a',
        inputPrompt: 'magenta',
        codeBg: '#100312',
        codeBorder: '#5e1b69',
        userMsgBg: '#310938',
        userMsgBorder: '#310938',
        userMsgText: 'magenta',
        diffRemovalBg: '#3a0c20',
        diffAdditionBg: '#200c3a',
        diffRemovalText: '#ff4d94',
        diffAdditionText: '#aa4dff',
        diffRemovalHighlightColor: '#ff1a75',
        diffRemovalHighlightBg: '#59002b',
        diffAdditionHighlightColor: '#bb66ff',
        diffAdditionHighlightBg: '#3b0059',
        diffRemovalNum: '#ff4d94',
        diffAdditionNum: '#aa4dff',
        diffRemovalPrefix: '#ff1a75',
        diffAdditionPrefix: '#bb66ff',
        primary: 'magenta',
        secondary: 'cyan',
        accent: 'purple',
        success: 'green',
        warning: 'yellow',
        danger: 'red',
        info: 'blue',
        statusOn: 'magenta',
        statusOff: '#7d2b8a',
        logoTextAnsi: '\x1b[1;35m',
        logoBodyAnsi: '\x1b[35m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#ff00ff', '#8800ff'],
    },
    {
        name: 'Glitch Matrix',
        text: '#00ff41',
        textMuted: '#00b32d',
        textDim: '#00661a',
        textInverted: 'black',
        border: '#00ff41',
        borderMuted: '#008020',
        borderDim: '#004d13',
        bg: undefined,
        cardBg: '#0d1f0d',
        highlightBg: '#122912',
        activeBg: '#1c3e1c',
        inputBg: '#122912',
        inputBorder: '#122912',
        inputText: '#00ff41',
        inputPlaceholder: '#00b32d',
        inputPrompt: '#ffff00',
        codeBg: '#040a04',
        codeBorder: '#008020',
        userMsgBg: '#122912',
        userMsgBorder: '#122912',
        userMsgText: '#00ff41',
        diffRemovalBg: '#3a001a',
        diffAdditionBg: '#003a10',
        diffRemovalText: '#ff0055',
        diffAdditionText: '#00ff66',
        diffRemovalHighlightColor: '#ff0033',
        diffRemovalHighlightBg: '#59001b',
        diffAdditionHighlightColor: '#33ff88',
        diffAdditionHighlightBg: '#005918',
        diffRemovalNum: '#ff0055',
        diffAdditionNum: '#00ff66',
        diffRemovalPrefix: '#ff0033',
        diffAdditionPrefix: '#33ff88',
        primary: '#00ff41',
        secondary: 'yellow',
        accent: 'cyan',
        success: '#00ff41',
        warning: 'yellow',
        danger: 'red',
        info: 'cyan',
        statusOn: '#00ff41',
        statusOff: '#00661a',
        logoTextAnsi: '\x1b[1;32m',
        logoBodyAnsi: '\x1b[32m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#00ff41', '#ffff00'],
    },
    {
        name: 'Warm Sunset',
        text: '#ffaa55',
        textMuted: '#cc8844',
        textDim: '#885522',
        textInverted: 'black',
        border: '#ff9933',
        borderMuted: '#aa6622',
        borderDim: '#663311',
        bg: undefined,
        cardBg: '#24180f',
        highlightBg: '#2e1e12',
        activeBg: '#422c1b',
        inputBg: '#2e1e12',
        inputBorder: '#2e1e12',
        inputText: '#ffaa55',
        inputPlaceholder: '#885522',
        inputPrompt: '#ff7733',
        codeBg: '#120c08',
        codeBorder: '#aa6622',
        userMsgBg: '#2e1e12',
        userMsgBorder: '#2e1e12',
        userMsgText: '#ffaa55',
        diffRemovalBg: '#3d120c',
        diffAdditionBg: '#3a2e0c',
        diffRemovalText: '#ff5544',
        diffAdditionText: '#ffcc33',
        diffRemovalHighlightColor: '#ff3322',
        diffRemovalHighlightBg: '#591108',
        diffAdditionHighlightColor: '#ffee44',
        diffAdditionHighlightBg: '#594400',
        diffRemovalNum: '#ff5544',
        diffAdditionNum: '#ffcc33',
        diffRemovalPrefix: '#ff3322',
        diffAdditionPrefix: '#ffee44',
        primary: '#ffaa55',
        secondary: '#ff7733',
        accent: 'magenta',
        success: '#ffcc33',
        warning: '#ff7733',
        danger: '#ff3322',
        info: '#ffaa55',
        statusOn: '#ffaa55',
        statusOff: '#885522',
        logoTextAnsi: '\x1b[1;33m',
        logoBodyAnsi: '\x1b[33m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#ff9933', '#ff0055'],
    },
    {
        name: 'Sakura Blossom',
        text: '#ffc0e0',
        textMuted: '#d98cb3',
        textDim: '#804d66',
        textInverted: 'black',
        border: '#ff99cc',
        borderMuted: '#aa4d7a',
        borderDim: '#662647',
        bg: undefined,
        cardBg: '#291320',
        highlightBg: '#331826',
        activeBg: '#472235',
        inputBg: '#331826',
        inputBorder: '#331826',
        inputText: '#ffc0e0',
        inputPlaceholder: '#804d66',
        inputPrompt: '#ff99cc',
        codeBg: '#140a10',
        codeBorder: '#aa4d7a',
        userMsgBg: '#331826',
        userMsgBorder: '#331826',
        userMsgText: '#ffc0e0',
        diffRemovalBg: '#3e0c1b',
        diffAdditionBg: '#1b3e2b',
        diffRemovalText: '#ff6699',
        diffAdditionText: '#66ffb3',
        diffRemovalHighlightColor: '#ff3377',
        diffRemovalHighlightBg: '#590022',
        diffAdditionHighlightColor: '#33ff99',
        diffAdditionHighlightBg: '#00592e',
        diffRemovalNum: '#ff6699',
        diffAdditionNum: '#66ffb3',
        diffRemovalPrefix: '#ff3377',
        diffAdditionPrefix: '#33ff99',
        primary: '#ffc0e0',
        secondary: '#ff99cc',
        accent: 'magenta',
        success: '#66ffb3',
        warning: 'yellow',
        danger: '#ff3377',
        info: '#ff99cc',
        statusOn: '#ffc0e0',
        statusOff: '#804d66',
        logoTextAnsi: '\x1b[1;35m',
        logoBodyAnsi: '\x1b[35m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#ffb3d9', '#ff3399'],
    },
    {
        name: 'Radioactive Slime',
        text: '#ccff00',
        textMuted: '#99cc00',
        textDim: '#669900',
        textInverted: '#0a0f00',
        border: '#ccff00',
        borderMuted: '#99cc00',
        borderDim: '#669900',
        bg: undefined,
        cardBg: '#0f1400',
        highlightBg: '#1a2400',
        activeBg: '#2a3b00',
        inputBg: '#1a2400',
        inputBorder: '#1a2400',
        inputText: '#ccff00',
        inputPlaceholder: '#669900',
        inputPrompt: '#cc00ff',
        codeBg: '#050a00',
        codeBorder: '#99cc00',
        userMsgBg: '#1a2400',
        userMsgBorder: '#1a2400',
        userMsgText: '#ccff00',
        diffRemovalBg: '#2a0033',
        diffAdditionBg: '#0f3300',
        diffRemovalText: '#ff00cc',
        diffAdditionText: '#00ff33',
        diffRemovalHighlightColor: '#ff33cc',
        diffRemovalHighlightBg: '#4d0066',
        diffAdditionHighlightColor: '#33ff66',
        diffAdditionHighlightBg: '#1a6600',
        diffRemovalNum: '#ff00cc',
        diffAdditionNum: '#00ff33',
        diffRemovalPrefix: '#ff33cc',
        diffAdditionPrefix: '#33ff66',
        primary: '#ccff00',
        secondary: '#cc00ff',
        accent: '#ff00cc',
        success: '#00ff33',
        warning: '#ffcc00',
        danger: '#ff0033',
        info: '#00ccff',
        statusOn: '#ccff00',
        statusOff: '#669900',
        logoTextAnsi: '\x1b[1;38;5;190m',
        logoBodyAnsi: '\x1b[38;5;190m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#ccff00', '#cc00ff'],
    },
    {
        name: 'Cosmic Void',
        text: '#f0f8ff',
        textMuted: '#a6aeb5',
        textDim: '#5e656e',
        textInverted: '#010103',
        border: '#f0f8ff',
        borderMuted: '#a6aeb5',
        borderDim: '#5e656e',
        bg: undefined,
        cardBg: '#05030d',
        highlightBg: '#0b081a',
        activeBg: '#171133',
        inputBg: '#0b081a',
        inputBorder: '#0b081a',
        inputText: '#f0f8ff',
        inputPlaceholder: '#5e656e',
        inputPrompt: '#ff007f',
        codeBg: '#020108',
        codeBorder: '#a6aeb5',
        userMsgBg: '#0b081a',
        userMsgBorder: '#0b081a',
        userMsgText: '#f0f8ff',
        diffRemovalBg: '#2e0a29',
        diffAdditionBg: '#091c33',
        diffRemovalText: '#ff33a6',
        diffAdditionText: '#33d6ff',
        diffRemovalHighlightColor: '#ff66c2',
        diffRemovalHighlightBg: '#5c1452',
        diffAdditionHighlightColor: '#66e0ff',
        diffAdditionHighlightBg: '#123866',
        diffRemovalNum: '#ff33a6',
        diffAdditionNum: '#33d6ff',
        diffRemovalPrefix: '#ff66c2',
        diffAdditionPrefix: '#66e0ff',
        primary: '#f0f8ff',
        secondary: '#ff007f',
        accent: '#9d00ff',
        success: '#33d6ff',
        warning: '#ffcc00',
        danger: '#ff0040',
        info: '#9d00ff',
        statusOn: '#f0f8ff',
        statusOff: '#5e656e',
        logoTextAnsi: '\x1b[1;38;5;231m',
        logoBodyAnsi: '\x1b[38;5;231m',
        logoMutedAnsi: '\x1b[38;5;240m',
        logoGradient: ['#ffffff', '#9d00ff'],
    },
    {
        name: 'Magma Eruption',
        text: '#ff4d00',
        textMuted: '#cc3d00',
        textDim: '#802600',
        textInverted: '#0d0300',
        border: '#ff4d00',
        borderMuted: '#cc3d00',
        borderDim: '#802600',
        bg: undefined,
        cardBg: '#1a0600',
        highlightBg: '#260a00',
        activeBg: '#401100',
        inputBg: '#260a00',
        inputBorder: '#260a00',
        inputText: '#ff4d00',
        inputPlaceholder: '#802600',
        inputPrompt: '#ffcc00',
        codeBg: '#080200',
        codeBorder: '#cc3d00',
        userMsgBg: '#260a00',
        userMsgBorder: '#260a00',
        userMsgText: '#ff4d00',
        diffRemovalBg: '#2e0a0a',
        diffAdditionBg: '#1f1400',
        diffRemovalText: '#ff3333',
        diffAdditionText: '#ffaa00',
        diffRemovalHighlightColor: '#ff6666',
        diffRemovalHighlightBg: '#5c1414',
        diffAdditionHighlightColor: '#ffcc33',
        diffAdditionHighlightBg: '#3d2900',
        diffRemovalNum: '#ff3333',
        diffAdditionNum: '#ffaa00',
        diffRemovalPrefix: '#ff6666',
        diffAdditionPrefix: '#ffcc33',
        primary: '#ff4d00',
        secondary: '#ffcc00',
        accent: '#ff0040',
        success: '#ffaa00',
        warning: '#ffff00',
        danger: '#ff0000',
        info: '#ff8800',
        statusOn: '#ff4d00',
        statusOff: '#802600',
        logoTextAnsi: '\x1b[1;38;5;202m',
        logoBodyAnsi: '\x1b[38;5;202m',
        logoMutedAnsi: '\x1b[38;5;236m',
        logoGradient: ['#ff4d00', '#ff0000'],
    }
];

export const THEMES = {
    Dark: {
        id: 'Dark',
        name: 'Dark (Default)',
        // Base Colors
        text: 'white',
        textMuted: 'gray',
        textDim: 'grey',
        textInverted: 'black',
        textExclusive: '#B5B8D9',
        textMutedExclusive: '#D4DEE7',
        
        // Borders
        border: 'white',
        borderMuted: 'gray',
        borderDim: 'grey',
        
        // Backgrounds
        bg: undefined,
        cardBg: '#1e1e1e',
        highlightBg: '#2a2a2a',
        activeBg: '#3a3a3a',
        
        // Input Box Colors
        inputBg: '#555555',
        inputBorder: '#555555',
        inputText: 'white',
        inputPlaceholder: '#cccccc',
        inputPrompt: 'white',
        
        // Code & Message Component Colors
        codeBg: '#1a1a1a',
        codeBorder: '#444444',
        userMsgBg: '#444444',
        userMsgBorder: '#444444',
        userMsgText: 'white',

        // Diff Component Palette
        diffRemovalBg: '#250808',
        diffAdditionBg: '#072410',
        diffRemovalText: '#885555',
        diffAdditionText: '#558866',
        diffRemovalHighlightColor: '#ff3333',
        diffRemovalHighlightBg: '#5a1818',
        diffAdditionHighlightColor: '#33ff66',
        diffAdditionHighlightBg: '#185a25',
        diffRemovalNum: '#d96868',
        diffAdditionNum: '#68d98c',
        diffRemovalPrefix: '#ff4d4d',
        diffAdditionPrefix: '#4dff88',
        
        // Accents & Indicators
        primary: 'white',
        secondary: 'cyan',
        accent: 'magenta',
        success: 'green',
        warning: 'yellow',
        danger: 'red',
        info: 'blue',
        
        // Status Indicators
        statusOn: 'white',
        statusOff: 'gray',

        // Logo / Terminal ANSI Colors
        logoTextAnsi: '\x1b[1;37m',
        logoBodyAnsi: '\x1b[37m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#0077ff', '#ff00ff'],
    },
    Light: {
        id: 'Light',
        name: 'Light',
        // Base Colors
        text: 'black',
        textMuted: 'gray',
        textDim: 'grey',
        textInverted: 'white',
        
        // Borders
        border: 'black',
        borderMuted: 'gray',
        borderDim: 'grey',
        
        // Backgrounds
        bg: undefined,
        cardBg: '#e5e5e5',
        highlightBg: '#d4d4d4',
        activeBg: '#c0c0c0',
        
        // Input Box Colors
        inputBg: '#d0d0d0',
        inputBorder: '#d0d0d0',
        inputText: 'black',
        inputPlaceholder: '#555555',
        inputPrompt: 'black',
        
        // Code & Message Component Colors
        codeBg: '#e8e8e8',
        codeBorder: '#b0b0b0',
        userMsgBg: '#d0d0d0',
        userMsgBorder: '#d0d0d0',
        userMsgText: 'black',

        // Diff Component Palette
        diffRemovalBg: '#fce8e8',
        diffAdditionBg: '#e6f9e6',
        diffRemovalText: '#661111',
        diffAdditionText: '#115511',
        diffRemovalHighlightColor: '#440000',
        diffRemovalHighlightBg: '#f8b4b4',
        diffAdditionHighlightColor: '#003300',
        diffAdditionHighlightBg: '#a6ebad',
        diffRemovalNum: '#c02020',
        diffAdditionNum: '#188028',
        diffRemovalPrefix: '#d01010',
        diffAdditionPrefix: '#109020',
        
        // Accents & Indicators
        primary: 'black',
        secondary: 'blue',
        accent: 'magenta',
        success: 'green',
        warning: 'yellow',
        danger: 'red',
        info: 'blue',
        
        // Status Indicators
        statusOn: 'black',
        statusOff: 'gray',

        // Logo / Terminal ANSI Colors
        logoTextAnsi: '\x1b[1;30m',
        logoBodyAnsi: '\x1b[30m',
        logoMutedAnsi: '\x1b[38;5;244m',
        logoGradient: ['#0077ff', '#ff00ff'],
    },
    'GitHub Dark': {
        id: 'GitHub Dark',
        name: 'GitHub Dark',
        // Base Colors
        text: '#c9d1d9',
        textMuted: '#8b949e',
        textDim: '#6e7681',
        textInverted: '#0d1117',
        
        // Borders
        border: '#30363d',
        borderMuted: '#30363d',
        borderDim: '#21262d',
        
        // Backgrounds
        bg: undefined,
        cardBg: '#161b22',
        highlightBg: '#21262d',
        activeBg: '#30363d',
        
        // Input Box Colors
        inputBg: '#21262d',
        inputBorder: '#21262d',
        inputText: '#c9d1d9',
        inputPlaceholder: '#8b949e',
        inputPrompt: '#58a6ff',
        
        // Code & Message Component Colors
        codeBg: '#0d1117',
        codeBorder: '#30363d',
        userMsgBg: '#21262d',
        userMsgBorder: '#21262d',
        userMsgText: '#c9d1d9',

        // Diff Component Palette
        diffRemovalBg: '#3c1e1e',
        diffAdditionBg: '#11381e',
        diffRemovalText: '#f85149',
        diffAdditionText: '#3fb950',
        diffRemovalHighlightColor: '#ff7b72',
        diffRemovalHighlightBg: '#701c1c',
        diffAdditionHighlightColor: '#56d364',
        diffAdditionHighlightBg: '#116329',
        diffRemovalNum: '#f85149',
        diffAdditionNum: '#3fb950',
        diffRemovalPrefix: '#f85149',
        diffAdditionPrefix: '#3fb950',
        
        // Accents & Indicators
        primary: '#c9d1d9',
        secondary: '#58a6ff',
        accent: '#bc8cff',
        success: '#3fb950',
        warning: '#d29922',
        danger: '#f85149',
        info: '#58a6ff',
        
        // Status Indicators
        statusOn: '#58a6ff',
        statusOff: '#8b949e',

        // Logo / Terminal ANSI Colors
        logoTextAnsi: '\x1b[1;36m',
        logoBodyAnsi: '\x1b[37m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#2ea043', '#56d364'],
    },
    'GitHub Light': {
        id: 'GitHub Light',
        name: 'GitHub Light',
        // Base Colors
        text: '#24292f',
        textMuted: '#57606a',
        textDim: '#6e7781',
        textInverted: '#ffffff',
        
        // Borders
        border: '#d0d7de',
        borderMuted: '#d0d7de',
        borderDim: '#e1e4e8',
        
        // Backgrounds
        bg: undefined,
        cardBg: '#f6f8fa',
        highlightBg: '#eaeef2',
        activeBg: '#d0d7de',
        
        // Input Box Colors
        inputBg: '#eaeef2',
        inputBorder: '#eaeef2',
        inputText: '#24292f',
        inputPlaceholder: '#57606a',
        inputPrompt: '#0969da',
        
        // Code & Message Component Colors
        codeBg: '#ffffff',
        codeBorder: '#d0d7de',
        userMsgBg: '#eaeef2',
        userMsgBorder: '#eaeef2',
        userMsgText: '#24292f',

        // Diff Component Palette
        diffRemovalBg: '#ffebe9',
        diffAdditionBg: '#e6ffec',
        diffRemovalText: '#cf222e',
        diffAdditionText: '#1a7f37',
        diffRemovalHighlightColor: '#82071e',
        diffRemovalHighlightBg: '#ffc1c0',
        diffAdditionHighlightColor: '#116329',
        diffAdditionHighlightBg: '#acf2bd',
        diffRemovalNum: '#cf222e',
        diffAdditionNum: '#1a7f37',
        diffRemovalPrefix: '#cf222e',
        diffAdditionPrefix: '#1a7f37',
        
        // Accents & Indicators
        primary: '#24292f',
        secondary: '#0969da',
        accent: '#8250df',
        success: '#1a7f37',
        warning: '#9a6700',
        danger: '#cf222e',
        info: '#0969da',
        
        // Status Indicators
        statusOn: '#0969da',
        statusOff: '#57606a',

        // Logo / Terminal ANSI Colors
        logoTextAnsi: '\x1b[1;34m',
        logoBodyAnsi: '\x1b[30m',
        logoMutedAnsi: '\x1b[38;5;244m',
        logoGradient: ['#1a7f37', '#2da44e'],
    },
    'Transparent Dark': {
        id: 'Transparent Dark',
        name: 'Transparent Dark',
        // Base Colors
        text: 'white',
        textMuted: 'gray',
        textDim: 'grey',
        textInverted: 'black',
        
        // Borders
        border: 'gray',
        borderMuted: 'gray',
        borderDim: 'grey',
        
        // Backgrounds (All transparent / undefined)
        bg: undefined,
        cardBg: undefined,
        highlightBg: '#2a2a2a',
        activeBg: '#3a3a3a',
        
        // Input Box Colors
        inputBg: '#555555',
        inputBorder: '#555555',
        inputText: 'white',
        inputPlaceholder: '#cccccc',
        inputPrompt: 'white',
        
        // Code & Message Component Colors
        codeBg: undefined,
        codeBorder: 'gray',
        userMsgBg: '#555555',
        userMsgBorder: '#555555',
        userMsgText: 'white',

        // Diff Component Palette (Transparent background, colored lines)
        diffRemovalBg: undefined,
        diffAdditionBg: undefined,
        diffRemovalText: '#ff6666',
        diffAdditionText: '#66ff66',
        diffRemovalHighlightColor: '#ff3333',
        diffRemovalHighlightBg: undefined,
        diffAdditionHighlightColor: '#33ff66',
        diffAdditionHighlightBg: undefined,
        diffRemovalNum: '#ff6666',
        diffAdditionNum: '#66ff66',
        diffRemovalPrefix: '#ff4d4d',
        diffAdditionPrefix: '#4dff88',
        
        // Accents & Indicators
        primary: 'white',
        secondary: 'cyan',
        accent: 'magenta',
        success: 'green',
        warning: 'yellow',
        danger: 'red',
        info: 'blue',
        
        // Status Indicators
        statusOn: 'white',
        statusOff: 'gray',

        // Logo / Terminal ANSI Colors
        logoTextAnsi: '\x1b[1;37m',
        logoBodyAnsi: '\x1b[37m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#0077ff', '#ff00ff'],
    },
    'Transparent Light': {
        id: 'Transparent Light',
        name: 'Transparent Light',
        // Base Colors
        text: 'black',
        textMuted: 'gray',
        textDim: 'grey',
        textInverted: 'white',
        
        // Borders
        border: 'gray',
        borderMuted: 'gray',
        borderDim: 'grey',
        
        // Backgrounds (All transparent / undefined)
        bg: undefined,
        cardBg: undefined,
        highlightBg: '#d4d4d4',
        activeBg: '#c0c0c0',
        
        // Input Box Colors
        inputBg: '#d0d0d0',
        inputBorder: '#d0d0d0',
        inputText: 'black',
        inputPlaceholder: '#555555',
        inputPrompt: 'black',
        
        // Code & Message Component Colors
        codeBg: undefined,
        codeBorder: 'gray',
        userMsgBg: '#d0d0d0',
        userMsgBorder: '#d0d0d0',
        userMsgText: 'black',

        // Diff Component Palette (Transparent background, colored lines)
        diffRemovalBg: undefined,
        diffAdditionBg: undefined,
        diffRemovalText: '#c02020',
        diffAdditionText: '#188028',
        diffRemovalHighlightColor: '#800000',
        diffRemovalHighlightBg: undefined,
        diffAdditionHighlightColor: '#004000',
        diffAdditionHighlightBg: undefined,
        diffRemovalNum: '#c02020',
        diffAdditionNum: '#188028',
        diffRemovalPrefix: '#d01010',
        diffAdditionPrefix: '#109020',
        
        // Accents & Indicators
        primary: 'black',
        secondary: 'blue',
        accent: 'magenta',
        success: 'green',
        warning: 'yellow',
        danger: 'red',
        info: 'blue',
        
        // Status Indicators
        statusOn: 'black',
        statusOff: 'gray',

        // Logo / Terminal ANSI Colors
        logoTextAnsi: '\x1b[1;30m',
        logoBodyAnsi: '\x1b[30m',
        logoMutedAnsi: '\x1b[38;5;244m',
        logoGradient: ['#0077ff', '#ff00ff'],
    },
    'Synthwave 84': {
        id: 'Synthwave 84',
        name: 'Synthwave 84',
        text: '#fdfdfd',
        textMuted: '#a08eb7',
        textDim: '#705c8a',
        textInverted: '#1a1025',
        textExclusive: '#e3dcf0',
        textMutedExclusive: '#b9abc9',
        border: '#fc28a8',
        borderMuted: '#a21568',
        borderDim: '#5c0a3a',
        bg: undefined,
        cardBg: '#261b38',
        highlightBg: '#35254d',
        activeBg: '#4c3570',
        inputBg: '#35254d',
        inputBorder: '#35254d',
        inputText: '#fdfdfd',
        inputPlaceholder: '#a08eb7',
        inputPrompt: '#03e8fc',
        codeBg: '#1e142b',
        codeBorder: '#a21568',
        userMsgBg: '#35254d',
        userMsgBorder: '#35254d',
        userMsgText: '#fdfdfd',
        diffRemovalBg: '#471434',
        diffAdditionBg: '#144743',
        diffRemovalText: '#ff4081',
        diffAdditionText: '#00e5ff',
        diffRemovalHighlightColor: '#ff79a1',
        diffRemovalHighlightBg: '#6b1e4e',
        diffAdditionHighlightColor: '#66f5ff',
        diffAdditionHighlightBg: '#1e6b65',
        diffRemovalNum: '#ff4081',
        diffAdditionNum: '#00e5ff',
        diffRemovalPrefix: '#ff79a1',
        diffAdditionPrefix: '#66f5ff',
        primary: '#fdfdfd',
        secondary: '#03e8fc',
        accent: '#fc28a8',
        success: '#00e5ff',
        warning: '#ffc107',
        danger: '#ff4081',
        info: '#b388ff',
        statusOn: '#03e8fc',
        statusOff: '#a08eb7',
        logoTextAnsi: '\x1b[1;35m',
        logoBodyAnsi: '\x1b[35m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#fc28a8', '#03e8fc'],
    },
    'Forest Sprite': {
        id: 'Forest Sprite',
        name: 'Forest Sprite',
        text: '#d6e6d1',
        textMuted: '#95b38d',
        textDim: '#628059',
        textInverted: '#161c14',
        textExclusive: '#eaf2e8',
        textMutedExclusive: '#a9c7a2',
        border: '#74a862',
        borderMuted: '#477038',
        borderDim: '#2b4720',
        bg: undefined,
        cardBg: '#1f291c',
        highlightBg: '#2a3826',
        activeBg: '#3a4d35',
        inputBg: '#2a3826',
        inputBorder: '#2a3826',
        inputText: '#d6e6d1',
        inputPlaceholder: '#95b38d',
        inputPrompt: '#8feb73',
        codeBg: '#161e14',
        codeBorder: '#477038',
        userMsgBg: '#2a3826',
        userMsgBorder: '#2a3826',
        userMsgText: '#d6e6d1',
        diffRemovalBg: '#3b231c',
        diffAdditionBg: '#203b1c',
        diffRemovalText: '#db6242',
        diffAdditionText: '#59cc3f',
        diffRemovalHighlightColor: '#f0896c',
        diffRemovalHighlightBg: '#5c362a',
        diffAdditionHighlightColor: '#80e368',
        diffAdditionHighlightBg: '#305929',
        diffRemovalNum: '#db6242',
        diffAdditionNum: '#59cc3f',
        diffRemovalPrefix: '#f0896c',
        diffAdditionPrefix: '#80e368',
        primary: '#d6e6d1',
        secondary: '#8feb73',
        accent: '#e69835',
        success: '#59cc3f',
        warning: '#e69835',
        danger: '#db6242',
        info: '#73b4eb',
        statusOn: '#8feb73',
        statusOff: '#95b38d',
        logoTextAnsi: '\x1b[1;32m',
        logoBodyAnsi: '\x1b[32m',
        logoMutedAnsi: '\x1b[90m',
        logoGradient: ['#8feb73', '#e69835'],
    }
};

export const MYSTERY_PRESETS = CHAOS_PRESETS;

let cachedChaosPreset = null;

/**
 * Resets the cached chaos preset so a new random preset will be picked on the next call.
 */
export const resetChaosTheme = () => {
    cachedChaosPreset = null;
};

/**
 * Returns theme colors for a given theme name (defaults to 'Dark')
 * @param {string} themeName 
 * @returns {object} Theme color palette object
 */
export const getThemeColors = (themeName = 'Dark') => {
    let colors;
    if (themeName === 'Mystery' || themeName === 'Chaos') {
        if (!cachedChaosPreset) {
            cachedChaosPreset = CHAOS_PRESETS[Math.floor(Math.random() * CHAOS_PRESETS.length)];
        }
        colors = { ...cachedChaosPreset, id: 'Mystery' };
    } else {
        // Clear cached chaos preset when active theme is non-chaos,
        // ensuring a fresh random chaos preset next time Chaos theme is selected.
        cachedChaosPreset = null;

        if (THEMES[themeName]) colors = THEMES[themeName];
        else if (themeName === 'GitHub') colors = THEMES['GitHub Dark'];
        else if (themeName === 'Transparent') colors = THEMES['Transparent Dark'];
        else colors = THEMES.Dark;
    }

    const codeColor = colors.codeText || colors.secondary || colors.info || (colors.logoGradient && colors.logoGradient[0]) || 'cyan';
    return { ...colors, codeText: codeColor };
};
