import fs from 'fs-extra';
import path from 'path';
import HTMLtoDOCX from 'html-to-docx';
import { parseArgs } from '../utils/arg_parser.js';

/**
 * Write DOCX Tool
 * Converts HTML content to a Word Document (.docx)
 */
export const write_docx = async (args) => {
    const {
        path: targetPath,
        content
    } = parseArgs(args);

    if (!targetPath) return 'ERROR: Missing "path" argument for write_docx.';
    if (!content) return 'ERROR: Missing "content" (HTML) for write_docx.';

    const absolutePath = path.resolve(process.cwd(), targetPath);

    try {
        // Ensure directory exists
        await fs.ensureDir(path.dirname(absolutePath));

        // Generate DOCX Buffer
        const fileName = path.basename(targetPath);
        const fullHtml = content.includes('<html') ? content : `
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <title>FluxFlow Document</title>
            </head>
            <body>
                ${content}
            </body>
            </html>
        `;

        const docxBuffer = await HTMLtoDOCX(fullHtml, null, {
            title: `FluxFlow_${fileName}`,
            creator: 'FluxFlow CLI',
            description: 'Generated by Agentic AI System',
            table: { row: { cantSplit: true } },
            footer: true,
            pageNumber: true,
        });

        // Write to disk
        await fs.writeFile(absolutePath, docxBuffer);

        return `SUCCESS: Word document [${targetPath}] generated successfully.\n- Size: ${(docxBuffer.length / 1024).toFixed(1)} KB`;
    } catch (err) {
        return `ERROR: Failed to generate DOCX [${targetPath}]: ${err.message}`;
    }
};
