import puppeteer from 'puppeteer';
import path from 'path';
import fs from 'fs-extra';
import { PDFDocument } from 'pdf-lib';
import { parseArgs } from '../utils/arg_parser.js';

/**
 * Write PDF Tool (Stable Puppeteer Version)
 * Uses bundled Chromium for 100% consistent rendering across all platforms.
 */
export const write_pdf = async (args) => {
    const {
        path: targetPath,
        content,
        orientation = 'portrait',
        margin = '10px'
    } = parseArgs(args);

    if (!targetPath) return 'ERROR: Missing "path" argument for write_pdf.';
    if (!content) return 'ERROR: Missing "content" (HTML/CSS) for write_pdf.';

    const absolutePath = path.resolve(process.cwd(), targetPath);
    let browser = null;

    try {
        // Ensure directory exists
        await fs.ensureDir(path.dirname(absolutePath));

        // Launch the bundled Chromium
        browser = await puppeteer.launch({
            headless: true,
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-gpu',
                '--disable-dev-shm-usage'
            ]
        });

        const page = await browser.newPage();

        // Inject global print styles to ensure multi-page consistency
        const styledContent = `
            <style>
                @page {
                    margin: ${margin};
                }
                body {
                    margin: 0;
                    padding: 0;
                    font-family: system-ui, -apple-system, sans-serif;
                }
                * { box-sizing: border-box; }
                .watermark {
                    position: fixed;
                    top: 50%;
                    left: 50%;
                    transform: translate(-50%, -50%) rotate(-50deg);
                    font-size: 52px;
                    font-weight: bold;
                    color: rgba(0, 0, 0, 0.005);
                    pointer-events: none;
                    z-index: -1000;
                    text-align: center;
                    width: 150%;
                    white-space: nowrap;
                    text-transform: uppercase;
                    letter-spacing: 5px;
                }
            </style>
            <div class="watermark">Generated by FluxFlow CLI (AI)</div>
            ${content}
        `;

        // Set HTML content
        await page.setContent(styledContent, { waitUntil: 'networkidle0' });

        // Generate PDF Buffer
        const pdfBytes = await page.pdf({
            format: 'A4',
            landscape: orientation.toLowerCase() === 'landscape',
            margin: {
                top: margin,
                right: margin,
                bottom: margin,
                left: margin
            },
            printBackground: true
        });

        // --- PDF-LIB METADATA INJECTION (Hardcoded Branded Metadata) ---
        const pdfDoc = await PDFDocument.load(pdfBytes);

        const fileName = path.basename(targetPath);
        pdfDoc.setTitle(`FluxFlow ${fileName}`);
        pdfDoc.setAuthor('FluxFlow CLI');
        pdfDoc.setSubject('Generated with AI');
        pdfDoc.setKeywords(['FluxFlow', 'AI', 'Agentic', 'Automated']);
        pdfDoc.setCreator('FluxFlow PDF Engine');
        pdfDoc.setProducer('FluxFlow (Generative AI)');

        const finalPdfBytes = await pdfDoc.save();
        await fs.writeFile(absolutePath, finalPdfBytes);

        const stats = await fs.stat(absolutePath);
        return `SUCCESS: PDF generated successfully at [${targetPath}] (${(stats.size / 1024).toFixed(2)} KB).`;
    } catch (err) {
        return `ERROR: Failed to generate PDF [${targetPath}]: ${err.message}`;
    } finally {
        // Cleanup
        if (browser) await browser.close();
    }
};
